# https://squidfunk.github.io/mkdocs-material/getting-started
# https://squidfunk.github.io/mkdocs-material/reference/admonitions
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml


site_name: NsPanel Lovelace UI Docs
site_description: Custom Firmware for NsPanel with the design of HomeAssistant's lovelace UI in mind, works with Tasmota.
site_author: Johannes Braun
site_url: https://jobr99.github.io/nspanel-lovelace-ui

repo_name: jobr99/nspanel-lovelace-ui
repo_url: https://github.com/jobr99/nspanel-lovelace-ui
edit_uri: ""

copyright: "Copyright &copy; 2023 Johannes Braun"

docs_dir: docs

theme:
    #logo: _assets/logo.png
    #favicon: _assets/favicon.ico
    name: material
    palette:
        accent: blue
    font:
        text: "arial, sans-serif"
        code: monospace
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.top
        - navigation.tracking
        - navigation.expand
        - search.highlight
        - search.share
        - search.suggest
    custom_dir: docs/overrides

extra_css:
    - _assets/user.css

extra:
  analytics:
    provider: custom
  version:
    provider: mike

markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
#    - markdown_include.include:
#        base_path: docs

plugins:
    - search:
        lang: en
    - mkdocs-video

nav:
    - "Overview": index.md
    - "Getting started (Home Assistant)":
        - "First steps":
            - "Prepare NsPanel": prepare_nspanel.md
            - "Prepare Home Assistant": prepare_ha.md
            - "Configure MQTT": configure_mqtt.md
        - "FAQ": faq.md
    - "Configuration - apps.yaml (Home Assistant)":
        - "Overview": config-overview.md
        - "Screensaver": config-screensaver.md
        - "Cards":
            - "Entities Card": card-entities.md
            - "Grid Card": card-grid.md
            - "Climate/Thermo Card": card-climate.md
            - "Media Card": card-media.md
            - "Alarm Card": card-alarm.md
            - "Wifi/QR Card": card-qr.md
            - "Power Card": card-power.md
            - "Unlock Card": card-unlock.md
        - "Special Settings for Entities": entities.md
        - "Subpages": subpages.md
        - "Notifications": notifications.md
        - "Physical Buttons": phys-btn.md

    - "Getting started (ioBroker)":
        - "Prepare NsPanel": prepare_nspanel_ioBroker.md
        - "Prepare ioBroker": iobroker-install.md
